using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using System.Threading.Tasks;
using CoinTweaker.Settings;
using CoinTweaker.Utils;

//object.EditorID checks the name

namespace CoinTweaker
{
    public class Program
    {
        static Lazy<GeneralSettings> _Settings = null!;
        static GeneralSettings Settings => _Settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "Settings.json", out _Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynMundu.esp")
                .Run(args);
        }

        public class CoinsToModify
        {
            public static List<TestObject> CoinWeightList = new List<TestObject>(new TestObject[] {
                new TestObject("Gold001", Settings.Name.RenameVanillaGoldCoinTo, Settings.Weight.VanillaGoldWeight, 1),
                new TestObject("Gold002", Settings.Name.RenameCoinsofTamrielSilverCoinTo, Settings.Weight.CoinsofTamrielSilverCoinWeight, Settings.Value.RevalueCoinsofTamrielSilverCoinTo),
                new TestObject("Gold003", Settings.Name.RenameCoinsofTamrielGoldCoinTo, Settings.Weight.CoinsofTamrielGoldCoinWeight, Settings.Value.RevalueCoinsofTamrielGoldCoinTo),
                new TestObject("nl_CursedCoin", Settings.Name.RenameNarrativeLootAncientCoinTo, Settings.Weight.NarrativeLootAncientCoinWeight, Settings.Value.RevalueNarrativeLootAncientCoinTo),
                new TestObject("BSKAyleidGold001", Settings.Name.RenameBeyondSkyrimAyleidCoinTo, Settings.Weight.BeyondSkyrimAyleidCoinWeight, Settings.Value.RevalueBeyondSkyrimAyleidCoinTo),
                new TestObject("AAAA_DwarvenCoin", Settings.Name.RenameUniqueCoinsDwarvernCoinTo, Settings.Weight.UniqueCoinsDwarvernCoinWeight, Settings.Value.RevalueUniqueCoinsDwarvernCoinTo),
                new TestObject("AAAA_NordicCoin", Settings.Name.RenameUniqueCoinsNordicCoinTo, Settings.Weight.UniqueCoinsNordicCoinWeight, Settings.Value.RevalueUniqueCoinsNordicCoinTo),
            });
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            foreach (IMiscItemGetter item in state.LoadOrder.PriorityOrder.WinningOverrides<IMiscItemGetter>())
            {
                foreach (var CoinObject in CoinsToModify.CoinWeightList)
                {
                    if (!item.EditorID?.Contains(CoinObject.EditorID, StringComparison.OrdinalIgnoreCase) ?? true) continue;
                    Console.WriteLine($"Modifying found Coin: {item.Name}");

                    var SelectedItem = state.PatchMod.MiscItems.GetOrAddAsOverride(item);

                    if (Settings.Weight.ReweightCoins == true)
                        SelectedItem.Weight = CoinObject.Weight;
                    if (Settings.Name.RenameCoins == true)
                        SelectedItem.Name = CoinObject.Name;
                    if (Settings.Value.RevalueCoins == true)
                        SelectedItem.Value = CoinObject.Value;
                }
            }
        }
    }
}
